    n_samples: 500
    response_type: "response"

    # trial params
    trial_range: [151,200] # 10 

    # baseline firing rate params
    baseline_threshold: False
    baseline_scale: False
    baseline_range: [0.1, 15]
    
    # beta params
    beta_a_range: [1, 1.5]
    beta_multiplier_range: [1.5, 2]

    # response params
    duration_range: [0.25, 0.7] # 0.4
    
    latency_range: [0.250, 0.410] # 0.35
    
    baseline_T: 2
    stimulus_T: 2
    dt: 0.001
    induce_refractory_period: True

    gain_response_fr_threshold: 5
    gain_response_fr_scale: 1

    # supplementary trials params
    generate_supplementary_trials: True
    
    supplementary_default_count: 200
    supplementary_default_factor: 5

    seed: 73
    save_dir: "/media/al/darch/response_stats/datasets/main_1k_uniformBaseline_gainFRscale1_gainFRthreshold5" #  "/media/al/bitesized/datasets"
    save_language: "both"
