#!/usr/bin/env bash
set -euo pipefail

# Deploy Docusaurus build to the top-level /docs folder for GitHub Pages.
# Run this from the repo root:
#   ./deploy-gh-pages.sh

SITE_DIR="docs-site"
PUBLISH_DIR="docs"

if [ ! -d "$SITE_DIR" ]; then
  echo "Error: $SITE_DIR directory not found. Run this from the repo root."
  exit 1
fi

echo "Building Docusaurus site..."
cd "$SITE_DIR"

if [ ! -d "node_modules" ]; then
  echo "Installing npm dependencies..."
  npm install
fi

npm run build
cd ..

echo "Replacing top-level /$PUBLISH_DIR with fresh build output..."
rm -rf "$PUBLISH_DIR"
mkdir -p "$PUBLISH_DIR"
cp -a "$SITE_DIR/build/." "$PUBLISH_DIR/"

# Optional: preserve custom domain if GitHub Pages needs it.
# Uncomment and edit this if your CNAME file is not already generated by Docusaurus.
# echo "alanadarcher.com" > "$PUBLISH_DIR/CNAME"

echo "Build copied to /$PUBLISH_DIR."
echo
echo "Files now ready to commit:"
git status --short "$PUBLISH_DIR" "$SITE_DIR/src" "$SITE_DIR/docusaurus.config.ts" "$SITE_DIR/docusaurus.config.js" app.py 2>/dev/null || true
echo
echo "Next steps:"
echo "  git add $PUBLISH_DIR $SITE_DIR/src $SITE_DIR/docusaurus.config.ts $SITE_DIR/docusaurus.config.js app.py"
echo "  git commit -m \"Deploy Docusaurus site\""
echo "  git push"