    n_samples: 20
    response_type: "response"

    # trial params
    min_trial_num: 10
    scale_trial: 35

    # baseline firing rate params
    threshold: 1
    scale: 3

    # beta params
    beta_a_range: [1, 1.5]
    beta_multiplier_range: [1.5, 2]

    # response params
    duration_range: [0.3, 0.7]
    duration: null
    
    latency: 0.350
    
    baseline_T: 2
    stimulus_T: 2
    dt: 0.001
    induce_refractory_period: True

    gain_low_trial: 20
    gain_high_trial: 10

    # supplementary trials params
    generate_supplementary_trials: True
    supplementary_threshold: 50
    supplementary_default_count: 200
    supplementary_default_factor: 5

    seed: 73
    save_dir:  "/media/al/sansidk/simulated_responses/dev"